### ISSUE TITLE
Error when trying to show the menu

### ISSUE THREAD

**Issue by jllodra** [Positive-LABS/SlideActionsPlugin#4]
Hi, 

I'm getting this error when trying to swipe from the right to show the menu:

![image](https://cloud.githubusercontent.com/assets/273590/14456199/fa456696-00a3-11e6-8dd3-b78b2f9a5868.png)

Any hint? Using ST 2.4.1

PS: just to add more info, I'm using it on a list with **useComponents: true** with components using an **hbox** layout, etc. With useComponents: false and simple components it appears to work.

**Comment by comur** [comment]
Hi,

can you try to test it with a non production version to get real line numbers and file names ?

**Comment by jllodra** [comment]
Not related to the plug-in: (?)

![image](https://cloud.githubusercontent.com/assets/273590/14456701/951a6a34-00a6-11e6-8908-d06b3dec9bfe.png)

If I remove "use Components: true" and the "defaultType" property, it seems to work.
So the problem is that the plug-in is not working with list that use components as items.

**Comment by comur** [comment]
Ah ok, I misread your message, it does not work with useComponents: true ? It's possible, I will check if I already used it with this kind of list
